[versions]
agp = "8.13.0"
androidx-activityCompose = "1.11.0"
compose = "1.9.4"
compose-material3 = "1.4.0"
coroutines = "1.10.2"
hilt = "2.57.2"
kotlin = "2.2.21"
okhttp = "5.3.0"
navigation = "2.9.5"
paging = "3.3.6"
room = "2.8.3"
test = "1.7.0"
timber = "5.0.1"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-coil = { module = "io.coil-kt:coil-compose", version = "2.7.0" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-materialIcons = { module = "androidx.compose.material:material-icons-extended", version = "1.7.8" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
compose-paging = { module = "androidx.paging:paging-compose", version.ref = "paging" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview-android", version.ref = "compose" }
compose-ratingbar = { module = "io.github.a914-gowtham:compose-ratingbar", version = "1.2.3" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
db-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
db-room-kotlin = { module = "androidx.room:room-ktx", version.ref = "room" }
di-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
di-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
di-hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
jetpack-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
jetpack-core = { module = "androidx.core:core-ktx", version = "1.17.0" }
jetpack-navigationFragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
jetpack-paging = { module = "androidx.paging:paging-common-ktx", version.ref = "paging" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
net-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
net-okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
net-retrofit = { module = "com.squareup.retrofit2:retrofit", version = "3.0.0" }
net-retrofit-json = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version = "1.0.0" }

# JSON
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }

# Logging
logging-timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Testing
test-kotlin = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
test-junit = { module = "junit:junit", version = "4.13.2" }
test-junitExt = { module = "androidx.test.ext:junit", version = "1.3.0" }
test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }
test-runner = { module = "androidx.test:runner", version.ref = "test" }
test-rules = { module = "androidx.test:rules", version.ref = "test" }

[bundles]
compose = ["compose-animation", "compose-foundation", "compose-material3", "compose-materialIcons", "compose-navigation", "compose-paging", "compose-ui", "compose-tooling", "compose-preview", "compose-runtime"]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "dagger.hilt.android.plugin", version.ref = "hilt" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.3.0" }
